# Generated by Django 3.2.15 on 2024-05-31 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommessage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_room_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roommessage',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to='chat.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproommessage',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ws_room_messages', to='chat.grouproom'),
        ),
        migrations.AddField(
            model_name='grouproommessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ws_room_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproom',
            name='group_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_room_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproom',
            name='group_members',
            field=models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
